
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Controller\:
    resource: '%kernel.project_dir%/app/Controller'

  App\Module\:
    resource: '%kernel.project_dir%/app/Module'

  App\Module\TypeSystem\TypeResolverInterface:
    alias: App\Module\TypeSystem\TypeResolver

  App\Module\Indexing\Storage\InMemoryStorage:
    shared: true

  App\Module\Indexing\Storage\StorageInterface:
    alias: App\Module\Indexing\Storage\InMemoryStorage

  App\Module\Indexing\Storage\DebugStorageInterface:
    alias: App\Module\Indexing\Storage\InMemoryStorage
