
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Controller\:
    resource: '%kernel.project_dir%/app/Controller'

  App\Module\:
    resource: '%kernel.project_dir%/app/Module'

  App\Core\Cancellation\:
    resource: '%kernel.project_dir%/app/Core/Cancellation'

  App\Module\TypeSystem\TypeResolverInterface:
    alias: App\Module\TypeSystem\TypeResolver
