
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Controller\:
    resource: '%kernel.project_dir%/app/Controller'

  App\Module\:
    resource: '%kernel.project_dir%/app/Module'
