parameters:
  env(APP_LOGGER_NAME): 'php-lsp'
  app.logger.name: '%env(APP_LOGGER_NAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  app.logger.processor.psr:
    class: Monolog\Processor\PsrLogMessageProcessor

  app.logger.handler.prod:
    class: Monolog\Handler\StreamHandler
    arguments:
      $stream: '%kernel.logs_dir%/%kernel.environment%.log'
      $level: !php/enum Monolog\Level::Debug

  Psr\Log\LoggerInterface:
    class: Monolog\Logger
    arguments:
      $name: '%app.logger.name%'
    calls:
      - [ 'pushHandler', [ '@app.logger.handler.prod' ] ]
      - [ 'pushProcessor', [ '@app.logger.processor.psr' ] ]

when@dev:
  services:
    _defaults:
      autowire: true
      autoconfigure: true

    app.logger.handler.dev:
      class: Monolog\Handler\StreamHandler
      arguments:
        $stream: 'php://stderr'
        $level: !php/enum Monolog\Level::Debug

    Psr\Log\LoggerInterface:
      class: Monolog\Logger
      arguments:
        $name: '%app.logger.name%'
      calls:
        - [ 'pushHandler', [ '@app.logger.handler.dev' ] ]
        - [ 'pushHandler', [ '@app.logger.handler.prod' ] ]
        - [ 'pushProcessor', [ '@app.logger.processor.psr' ] ]



    Lsp\Workspace\File\FilesystemReader\FilesystemReaderFactory: ~
    Lsp\Workspace\File\FilesystemReader\FilesystemReaderFactoryInterface:
      class: Lsp\Workspace\File\FilesystemReader\FilesystemReaderFactory

    Lsp\Workspace\Project\ProjectFactory: ~
    Lsp\Workspace\Project\ProjectFactoryInterface:
      class: Lsp\Workspace\Project\ProjectFactory

    Lsp\Workspace\File\FileFactory: ~
    Lsp\Workspace\File\FileFactoryInterface:
      class: Lsp\Workspace\File\FileFactory

    App\Module\Document\InMemoryDocumentIdentifierFactory: ~
    App\Module\Document\DocumentIdentifierFactoryInterface:
      class: App\Module\Document\InMemoryDocumentIdentifierFactory

    App\Module\Document\LocalFileDocumentLoader: ~
    App\Module\Document\DocumentLoaderInterface:
      class: App\Module\Document\LocalFileDocumentLoader

    React\Filesystem\AdapterInterface:
      factory: [React\Filesystem\Factory, create]
