variant = "loose"

[[issues]]
file = "app/Controller/Debug/IndexGetController.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Controller/Debug/IndexKeysController.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Controller/Debug/IndexKeysController.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 3

[[issues]]
file = "app/Controller/Debug/IndexSearchController.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "app/Controller/TextDocument/DocumentSymbolController.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Controller/TextDocument/DocumentSymbolController.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "app/Controller/TextDocument/DocumentSymbolController.php"
code = "kan-defect"
message = "Class has a high kan defect score (2.74)."
count = 1

[[issues]]
file = "app/Controller/WorkspaceSymbolController.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Controller/WorkspaceSymbolController.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "app/Controller/WorkspaceSymbolController.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "app/Controller/WorkspaceSymbolController.php"
code = "kan-defect"
message = "Class has a high kan defect score (2.55)."
count = 1

[[issues]]
file = "app/Listener/DebugServerListener.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1

[[issues]]
file = "app/Module/CodeAction/ImportSymbolCodeActionContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (2)."
count = 1

[[issues]]
file = "app/Module/CodeAction/ImportSymbolCodeActionContributor.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "app/Module/CodeAction/RemoveUnusedImportCodeActionContributor.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "app/Module/Completion/ClassMemberCompletionContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Completion/ClassMemberCompletionContributor.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "app/Module/Completion/ClassMemberCompletionContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (2.3100000000000005)."
count = 1

[[issues]]
file = "app/Module/Completion/ClassMemberCompletionContributor.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 2

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "kan-defect"
message = "Class has a high kan defect score (3.6400000000000006)."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "literal-named-argument"
message = "Literal argument `'UTF-8'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "literal-named-argument"
message = "Literal argument `1` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "literal-named-argument"
message = "Literal argument `50` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "no-shorthand-ternary"
message = "Use of the shorthand ternary operator."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHtmlRenderer.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "kan-defect"
message = "Class has a high kan defect score (5.380000000000001)."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "literal-named-argument"
message = "Literal argument `3` should be passed as a named argument for clarity."
count = 2

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 3

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 2

[[issues]]
file = "app/Module/Debug/DebugHttpServer.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "app/Module/Declaration/ClassDeclarationContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Declaration/ClassDeclarationContributor.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "app/Module/Declaration/ClassDeclarationContributor.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "app/Module/Declaration/ClassDeclarationContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (1.9600000000000002)."
count = 1

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (1.61)."
count = 1

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 3

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "no-assign-in-condition"
message = "Avoid assignments in conditions."
count = 8

[[issues]]
file = "app/Module/Definition/ClassDefinitionContributor.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 8

[[issues]]
file = "app/Module/Definition/MethodDefinitionContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Documentation/ClassDocumentationContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Documentation/ClassDocumentationContributor.php"
code = "halstead"
message = "Method has a high halstead effort"
count = 1

[[issues]]
file = "app/Module/Documentation/ClassDocumentationContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (1.9800000000000002)."
count = 1

[[issues]]
file = "app/Module/Documentation/MethodDocumentationContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Implementation/InterfaceImplementationContributor.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Indexing/Data/ClassData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Data/ConstantData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Data/MethodData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Data/ParameterData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Data/PropertyData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Indexer.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Indexer/InheritanceIndexer.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Indexing/Indexer/InheritanceIndexer.php"
code = "kan-defect"
message = "Class has a high kan defect score (2.02)."
count = 1

[[issues]]
file = "app/Module/Indexing/IndexingStatus.php"
code = "literal-named-argument"
message = "Literal argument `3` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/DebugStorageInterface.php"
code = "too-many-methods"
message = "Interface has too many methods."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/InMemoryStorage.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/InMemoryStorage.php"
code = "kan-defect"
message = "Class has a high kan defect score (5.61)."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/InMemoryStorage.php"
code = "literal-named-argument"
message = "Literal argument `2` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/InMemoryStorage.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/IndexData/ClassData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/IndexData/ConstantData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/IndexData/MethodData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/Indexing/Storage/IndexData/PropertyData.php"
code = "excessive-parameter-list"
message = "Parameter list is too long."
count = 1

[[issues]]
file = "app/Module/PsiFile/FifoCache.php"
code = "literal-named-argument"
message = "Literal argument `1` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "app/Module/PsiFile/Tree.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/PsiFile/Tree.php"
code = "kan-defect"
message = "Class has a high kan defect score (3.5700000000000003)."
count = 1

[[issues]]
file = "app/Module/PsiFile/Tree.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "app/Module/References/VariableReferenceContributor.php"
code = "halstead"
message = "Method has a high halstead difficulty"
count = 1

[[issues]]
file = "app/Module/Signature/ConstructorSignatureContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Signature/ConstructorSignatureContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (1.7000000000000002)."
count = 1

[[issues]]
file = "app/Module/Signature/MethodSignatureContributor.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "app/Module/Signature/MethodSignatureContributor.php"
code = "kan-defect"
message = "Class has a high kan defect score (2.79)."
count = 1

[[issues]]
file = "app/Module/TypeDefinition/TypeDefinitionTypeContributor.php"
code = "no-else-clause"
message = "Avoid `elseif` clauses."
count = 1
